name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Task 2: Linting step
      - name: Lint code with flake8
        run: |
          pip install flake8
          flake8 .
          
      # Task 3: Test step
      - name: Run unit tests with nose
        run: |
          pip install nose
          nosetests
